#!/bin/bash
# SO3 - Adrián Alcántara - Módulo 1
#Alumno: Victerson Balbuena Medina (2025-1359)

# ============================================
# Comandos usados practica 1 (Instalacion del Sistema Operativo)
# ============================================
#(LINUX-MINT)
# instala las actualizaciones disponibles para los paquetes
Sudo apt update 
# Instala todas las actualizaciones disponibles automáticamente
sudo apt upgrade -y
============================================
Comandos usados practica 2 (Configuración de parametros de red)
============================================
(LINUX-MINT)
# Mostrar interfaces de red
ifconfig

# Eliminar y agregar IP manualmente
sudo ip addr del 192.168.100.75/24 dev ens33
sudo ip addr add 192.168.100.102/24 dev ens33

# Mostrar rutas
ip route show

# Agregar gateway
sudo ip route add default via 192.168.100.1 dev ens33
#Eliminar 
sudo ip route del default via 192.168.100.1 dev ens33
#DEFAULT 
sudo ip route del default

# Editar DNS
sudo nano /etc/resolv.conf
#----------AGREGA-------------
# nameserver 8.8.8.8
# nameserver 8.8.4.4
# -----------------------------
# Renovar DHCP
sudo dhclient -r
sudo dhclient

# ------------------------------NMCLI----------------------------------------------
# Mostrar conexiones de NetworkManager
nmcli con show

# Configuración manual de IP 
nmcli connection modify "Conexión cableada 1" ipv4.method manual ipv4.addresses 192.168.100.131/24 ipv4.gateway 192.168.100.1 ipv4.dns 8.8.8.8 ipv4.ignore-auto-dns yes

# --------------------------------DNS-----------------------------------------------
# usando 8.8.8.8 y 1.1.1.1:
sudo nmcli connection modify "Wired connection 1" ipv4.dns "8.8.8.8 1.1.1.1"

# Si está en DHCP, debes permitir que use DNS manual
sudo nmcli connection modify "Wired connection 1" ipv4.ignore-auto-dns yes

# Si quieres que use tanto DHCP DNS como manuales, pon:
sudo nmcli connection modify "Wired connection 1" ipv4.ignore-auto-dns no

# Reiniciar la conexión
sudo nmcli connection down "Wired connection 1"
sudo nmcli connection up "Wired connection 1"


# Probar conectividad
ping 8.8.8.8
ping 8.8.4.4

# ------------------------------ DHCP ----------------------------------------------
# ELIMINAR TODAS LAS DIRECCIONES IP DE FORMA STATICA 
sudo nmcli connection modify "Wired connection 1" ipv4.addresses ""
sudo nmcli connection modify "Wired connection 1" ipv4.gateway ""

# Configuración automática DHCP
nmcli connection modify "Conexión cableada 1" ipv4.method auto

# REINICIAR 
sudo nmcli connection down "Wired connection 1"
sudo nmcli connection up "Wired connection 1"

# ---------------------------   NETPLAN ----------------------------------------------
# Alternativa: Netplan (para algunas versiones de Linux Mint/Ubuntu)
cd /etc/netplan
ls
sudo nano 01-network-manager-all.yaml
# ----------------------------YML-----------------------------
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
        - 192.168.1.10/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
# -----------------------------------------------------------
sudo netplan apply
ip route
ping 8.8.8.8
ping 8.8.4.4

# ===========================================================================================================
# Comandos usados practica 3 (Gestion de Usuario y grupos)
# ===========================================================================================================
(LINUX-MINT)
# Crear usuario
sudo adduser victerson
groups victerson

# Agregar usuario a sudo
sudo usermod -aG sudo victerson
groups victerson

# Crear grupo
sudo addgroup guest
getent group

# Crear otro usuario
sudo adduser victor
sudo usermod -aG guest victor
groups victor

# Eliminar usuario de grupo
sudo gpasswd -d julian guest
groups victor

# Eliminar usuario y grupo
sudo deluser victor
sudo delgroup guest
getent group

(WINDOWS)
time /t
date /t

# ============================================
Comandos usados practica 4 (Gestion de Permisos de archivos)
# ============================================

(LINUX-MINT)
# Crear carpeta y archivo
mkdir MATERIA
cd MATERIA/
vi estudiante.txt
cat estudiante.txt

# Cambiar permisos del archivo
chmod 0 estudiante.txt

#PARA USUARIOS
chmod u+rwx estudiante.txt
#PARA GRUPOS
chmod g+rwx estudiante.txt
#PARA OTROS
chmod o+rwx estudiante.txt

ls -l

# Crear segunda carpeta y explorar directorios
cd ..
mkdir MATERIA2
cd MATERIA
clear
ls 
cd - 
cd MATERIA
cd ..
cd MATERIA2
ls
cd ..

# Copiar archivo a otra carpeta
cd MATERIA
cp estudiante.txt /home/miguel-20251367/Escritorio/MATERIA2
ls
z2 cd ..
cd MATERIA2
ls 
ls -l
cd ..

# Eliminar carpetas
rm -r MATERIA
ls
rm -r MATERIA2
ls
